language: rust
rust:
  - nightly-2018-11-24

before_script: |
  rustup component add rustfmt-preview clippy-preview
script: |
  cargo fmt --all -- --check &&
  cargo clippy --all -- -D clippy::all &&
  cargo build --all --verbose &&
  cargo test  --all --verbose
cache: cargo
